### ISSUE TITLE
Code Modularity (tictactoe-engine.js)

### ISSUE THREAD

**Issue by vijeth-aradhya** [vijeth-aradhya/tictactoe-engine#1]
Well, right now the code is gibberish but the engine is working fine. The code has to be **optimized** more, and should be **modular**.

Preferably, _objects_ must be used.

Please work on the other branch https://github.com/vijeth-aradhya/tictactoe-engine/tree/tictactoe-engine-basic (on the file tictactoe-engine.js)

**Comment by haydenwade** [comment]
Would you be opposed to using angular? It would clean up alot of the document.getElementById and eventListeners. You could also create the tic-tac-toe grid in real time, enhancing the UX

**Comment by vijeth-aradhya** [comment]
@haydenty The whole point of this project is to use only raw html, css ad JS
I certainly agree with you, either Angular or JQuery would've helped but you must use only JS to build the project

**Comment by adiman9** [comment]
This may be something I would be interested in doing. I will submit a PR if I get it done

**Comment by vijeth-aradhya** [comment]
@adiman9 That's awesome, thank you so much! A couple of pointers to keep in mind -
- Please try to use _objects_ to implement the algorithm
- A bit of _abstraction_ in the code would be great so that everyone can understand!
- Try not to change the course of the algorithm; just divide the code into smaller pieces and combine them to make it more _modular_.

**Comment by adiman9** [comment]
@vijeth-aradhya no problem

**Comment by vijeth-aradhya** [comment]
@adiman9 Please note that there are some changes in the repository! (still working on the same branch)

**Comment by adiman9** [comment]
I saw, I will incorporate them into the changes I make

**Comment by adiman9** [comment]
I submitted #6 which should take care of this issue
