### ISSUE TITLE
Two player mode and single player mode to be merged into single project

### ISSUE THREAD

**Issue by vijeth-aradhya** [vijeth-aradhya/tictactoe-engine#4]
Currently, the single player mode is in the other branch and the two player mode is in the master branch. 

**They have to be in the same project like the user should be able to choose single/two player mode in the page.**

Please work in the other branch https://github.com/vijeth-aradhya/tictactoe-engine/tree/tictactoe-engine-basic

**Comment by dickyw71** [comment]
Hi Vijeth, I have taken a look and run both versions, the 1-player and 2-player, in a codepen. 
You would like a new project where the game is 1 or 2 player based on a user choice. 
Please let me if I mis-understood the issue.
I will add the  1 or 2 player choice and submit a PR to the tictactoe-engine-basic branch.

**Comment by vijeth-aradhya** [comment]
@dickyw71 Yes, I would like a **new proper, good-looking web page in terms of design** where I would like to give User a choice between two player mode and single player mode

A couple of pointers to keep in mind -
- The web page should look nice, since it is the first page the User interacts with
- When the User selects one of the modes, he should be redirected to another page which corresponds to that mode. And, then he continues the way it is right now.
- About the UI part, this is partially related to #2 

Looking forward to your PR!

**Comment by dickyw71** [comment]
Hi Vijeth, I have added a player selection option and merged the one-player and two-player modes into a single javascript file. I have tested it in this [codepen](http://codepen.io/dickyw71/pen/pEWELv)
No major page re-designing done but I have addressed the original issue (I think).
If you are happy with it I will create a PR.

**Comment by vijeth-aradhya** [comment]
@dickyw71 It looks good enough till now!
- I noticed that the _"reset condition"_ link is not working, can you please make it go to the original mode selection page when clicked?
- And, also can you split the functions, attributes, variables, basically the code related to each mode to a different JS file so that things become more modular? (like single-player.js and two-player.js) [ IF POSSIBLE ]

**Comment by dickyw71** [comment]
@vijeth-aradhya Thanks for the feedback.
Did the "reset condition" link work prior to my changes? 
I found that it did not work in codepen because the file path `'./tictactoe.html'` will be invalid in that environment.
If I did break that feature reject my PR but if not please accept my PR and create a new issue for the 'reset condition' bug.
I agree the code could be made more modular, by splitting and removing duplication, but this isn't a task I want to pick-up.

**Comment by dickyw71** [comment]
@vijeth-aradhya Good news, just tested on my local computer and reset works fine.

**Comment by vijeth-aradhya** [comment]
@dickyw71 I just checked it myself too! Wonder why it wasn't working on codepen

Anyways thank you so much for your contribution! :)

**Comment by dickyw71** [comment]
My pleasure I enjoyed working on it. Thanks for creating the issue, I may be able to do another in a few days. It really helps to keep each issue concise and SMART: Specific, Measureable, Achievable, Realistic and Time bound.
